### ISSUE TITLE
people storage format

### ISSUE THREAD

**Issue by ConnyOnny** [ZeckoVicath/Protokoller#1]
I suggest a php array in "config.php" of the form

`$people = array("Max Mustermann", "Marlene Musterfrau");`

instead of the complicated xml-based approach. This would remove the feature of having different "kinds" of persons (member, collaborator, guest). But that didn't show up in the generated protocol anyway, so I guess we can leave it out.

Opinions? Alternatives?

**Comment by ZeckoVicath** [comment]
I support that idea, the XML parsing can be implemented for specific forks/deployments.

**Comment by ConnyOnny** [comment]
Implemented. Now we just have to throw the old code out
